### ISSUE TITLE
test script or at least option to modify pages scraped

### ISSUE THREAD

**Issue by cdrani** [MarkelFe/metacritic-crawler#12]
There should be a way to test the scraping of say just one page. I think it scrapes 100 pages, but if someone wants to test a change in the code, would they have to run the script and just exit it after a minute and hope they have at least some data that they can verify their changes against?

**Comment by Markel** [comment]
I understand what you mean, but how the script works (as you know) is getting the games that metacritic has in games.py and later scraping them on analyze.py. The games are scraped and listed from [this website](https://www.metacritic.com/browse/games/score/metascore/all/all/filtered?sort=desc). The things is that in that website 100 games appear.

I think that the best that we could do is creating a dev folder in which we include a gm.jl with only one game by default (probably the one included on README.md for contrasting purposes). I don't know I mark the issue as discussion because I'm not very sure of what we can do with this one.

**Comment by Markel** [comment]
Should we close this issue now that #16 is merged?

**Comment by cdrani** [comment]
Yes.
